### ISSUE TITLE
Prestige Shop - Can not use nor see prestige.

### ISSUE THREAD

**Issue by THB0705** [8BitToaster/Grand-Expansion#5]
Regardless of whether I am using an import file or not, my prestige does not show up in the shop, and I can not use it in the shop. I can only display my prestige when click somewhere off the board. I do not know if this is an issue, or if the prestige shop feature is simply not finished.

**Comment by 8BitToaster** [comment]
I'm a bit confused why this is happening, but will definitely look into it. Your prestige can't simply "not show up in the shop" because it is a resource that if you have it can be accessed from all places in the game. I don't know if you beat the game/prestige you got more prestige, but I will look into it. 

-8BitToaster

**Comment by THB0705** [comment]
When I get back from uni, I'll take a peek at your code.

**Comment by 8BitToaster** [comment]
I uploaded the new version with the new save system that autosaves every 30 seconds. I also fixed some bugs so try out this new version. I want to add a feature where you can buy a bigger map from the prestige shop because right now your games can get to many tiles.

-8BitToaster

**Comment by THB0705** [comment]
Still can't see my prestige in the shop.

- Prestige in-game. 37...
![image](https://user-images.githubusercontent.com/42702031/51334916-22e44780-1a81-11e9-9d08-01cb52143ef2.png)

- Prestige that is shown in shop. 0...
![image](https://user-images.githubusercontent.com/42702031/51334965-35f71780-1a81-11e9-8115-fbffa674c083.png)

**Comment by 8BitToaster** [comment]
I'm so sorry. I should've made things more clear. That is the amount of prestige you get when you prestige which is what that thing is you buy right underneath it. Once you prestige a resource called prestige will show on your resource bar thing which shows how much you have. That is supposed to mean once you prestige you will get +37 prestige. Maybe I should change the names a little to make it less confusing, but I had it named that just till I thought of a good name. This is not a bug, but a misunderstanding

-8BitToaster
